package stories

import (
	"context"
	"errors"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// integrationStore is what the integration tests work with: the store under test
// plus the pool, so a test can insert the author a story requires.
type integrationStore struct {
	store  *PostgresStore
	pool   *pgxpool.Pool
	prefix string
	author string
}

// integrationSetup connects to the database named by KNOT_POSTGRES_DSN and
// creates an author to attach stories to.
//
// The test is skipped, not failed, when KNOT_POSTGRES_DSN is unset, when the
// database is unreachable, or when the tables have not been migrated yet — none
// of those is a defect in the code under test.
func integrationSetup(t *testing.T) integrationStore {
	t.Helper()

	dsn := strings.TrimSpace(os.Getenv("KNOT_POSTGRES_DSN"))
	if dsn == "" {
		t.Skip("KNOT_POSTGRES_DSN is not set; skipping PostgreSQL integration test")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Skipf("could not build a pool from KNOT_POSTGRES_DSN: %v", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		t.Skipf("PostgreSQL at KNOT_POSTGRES_DSN is not reachable: %v", err)
	}

	var migrated bool
	if err := pool.QueryRow(ctx, "SELECT to_regclass('public.stories') IS NOT NULL").Scan(&migrated); err != nil {
		pool.Close()
		t.Skipf("could not inspect the schema: %v", err)
	}
	if !migrated {
		pool.Close()
		t.Skip("the stories table does not exist; run `go run ./cmd/knot migrate up` first")
	}

	store, err := NewPostgresStore(pool)
	if err != nil {
		pool.Close()
		t.Fatalf("NewPostgresStore() error = %v, want nil", err)
	}

	prefix := fmt.Sprintf("knot-it-%d-", time.Now().UnixNano())

	var author string
	err = pool.QueryRow(
		ctx,
		`INSERT INTO users (email, password_hash, display_name, preferred_languages)
		 VALUES ($1, $2, $3, $4)
		 RETURNING id`,
		prefix+"author@example.test",
		"$argon2id$v=19$m=65536,t=1,p=4$c2FsdA$a2V5",
		"Integration Author",
		[]string{"eng"},
	).Scan(&author)
	if err != nil {
		pool.Close()
		t.Fatalf("could not create the integration author: %v", err)
	}

	t.Cleanup(func() {
		cleanupCtx, cancelCleanup := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancelCleanup()

		// Stories reference the author, so they go first even though the foreign
		// key cascades.
		if _, err := pool.Exec(cleanupCtx, "DELETE FROM stories WHERE author_id = $1", author); err != nil {
			t.Logf("cleanup: could not delete test stories: %v", err)
		}
		if _, err := pool.Exec(cleanupCtx, "DELETE FROM users WHERE email LIKE $1", prefix+"%"); err != nil {
			t.Logf("cleanup: could not delete test users: %v", err)
		}
		pool.Close()
	})

	return integrationStore{store: store, pool: pool, prefix: prefix, author: author}
}

// newIntegrationStory builds a story ready to insert, named so a failure names
// the case that produced the row.
func newIntegrationStory(author, name string) Story {
	return Story{
		AuthorID:            author,
		Pillar:              PillarHeritage,
		Language:            "eng",
		Title:               "Integration " + name,
		Body:                "Body for " + name,
		ApproximateLocation: "Cape Town",
		MediaURLs:           []string{"https://example.test/" + name + ".jpg"},
	}
}

func TestPostgresStoreCreateStoryRoundTrip(t *testing.T) {
	env := integrationSetup(t)
	ctx := context.Background()

	created, err := env.store.CreateStory(ctx, newIntegrationStory(env.author, "create"))
	if err != nil {
		t.Fatalf("CreateStory() error = %v, want nil", err)
	}

	if !isUUID(created.ID) {
		t.Errorf("id = %q, want a canonical uuid generated by the database", created.ID)
	}
	if created.AuthorID != env.author {
		t.Errorf("author id = %q, want %q", created.AuthorID, env.author)
	}
	if created.Pillar != PillarHeritage {
		t.Errorf("pillar = %q, want %q", created.Pillar, PillarHeritage)
	}
	if created.ApproximateLocation != "Cape Town" {
		t.Errorf("approximate location = %q, want %q", created.ApproximateLocation, "Cape Town")
	}
	if len(created.MediaURLs) != 1 {
		t.Errorf("media urls = %v, want one entry", created.MediaURLs)
	}
	if created.Sensitive {
		t.Error("sensitive = true, want the column default false")
	}
	if created.CreatedAt.IsZero() || created.UpdatedAt.IsZero() {
		t.Error("timestamps are zero, want database-generated values")
	}
	if !isUUID(created.RootVersionID) {
		t.Errorf("root version id = %q, want a canonical uuid", created.RootVersionID)
	}

	// The story's root version must really exist, parentless, carrying the
	// submitted content. Read with an independent query so the assertion does
	// not lean on the same join the fetch uses.
	var (
		versionID string
		parent    *string
		language  string
		title     string
		body      string
	)
	if err := env.pool.QueryRow(
		ctx,
		`SELECT id, parent_version_id, language, title, body FROM story_versions WHERE id = $1`,
		created.RootVersionID,
	).Scan(&versionID, &parent, &language, &title, &body); err != nil {
		t.Fatalf("could not read the root version: %v", err)
	}
	if versionID != created.RootVersionID {
		t.Errorf("root version id = %q, want %q", versionID, created.RootVersionID)
	}
	if parent != nil {
		t.Errorf("root version parent = %q, want NULL", *parent)
	}
	if language != created.Language || title != created.Title || body != created.Body {
		t.Errorf("root version content = (%q, %q, %q), want the submitted content", language, title, body)
	}

	fetched, err := env.store.GetStory(ctx, created.ID)
	if err != nil {
		t.Fatalf("GetStory() error = %v, want nil", err)
	}
	if fetched.ID != created.ID || fetched.Title != created.Title || fetched.Body != created.Body {
		t.Errorf("fetched = %+v, want it to match the created story %+v", fetched, created)
	}
	if !fetched.CreatedAt.Equal(created.CreatedAt) {
		t.Errorf("created at = %v, want %v", fetched.CreatedAt, created.CreatedAt)
	}
}

func TestPostgresStoreCreateStoryWithoutOptionalFields(t *testing.T) {
	env := integrationSetup(t)
	ctx := context.Background()

	story := newIntegrationStory(env.author, "sparse")
	story.ApproximateLocation = ""
	story.MediaURLs = nil

	created, err := env.store.CreateStory(ctx, story)
	if err != nil {
		t.Fatalf("CreateStory() error = %v, want nil", err)
	}

	if created.ApproximateLocation != "" {
		t.Errorf("approximate location = %q, want empty for a NULL column", created.ApproximateLocation)
	}
	if created.MediaURLs == nil {
		t.Error("media urls = nil, want an empty slice for a TEXT[] NOT NULL column")
	}
	if len(created.MediaURLs) != 0 {
		t.Errorf("media urls = %v, want no entries", created.MediaURLs)
	}
}

func TestPostgresStoreGetStoryUnknownId(t *testing.T) {
	env := integrationSetup(t)

	_, err := env.store.GetStory(context.Background(), "99999999-9999-4999-8999-999999999999")
	if !errors.Is(err, ErrNotFound) {
		t.Errorf("errors.Is(err, ErrNotFound) = false, want true (err = %v)", err)
	}
}

func TestPostgresStoreGetStoryMalformedId(t *testing.T) {
	env := integrationSetup(t)

	_, err := env.store.GetStory(context.Background(), "not-a-uuid")
	if !errors.Is(err, ErrNotFound) {
		t.Errorf("errors.Is(err, ErrNotFound) = false, want true (err = %v)", err)
	}
}

// authoredIDs returns this test's story ids in feed order, read with an
// independent query so the pagination assertions are not circular.
func authoredIDs(t *testing.T, env integrationStore) []string {
	t.Helper()

	rows, err := env.pool.Query(
		context.Background(),
		`SELECT id FROM stories WHERE author_id = $1 ORDER BY created_at DESC, id DESC`,
		env.author,
	)
	if err != nil {
		t.Fatalf("could not read the expected order: %v", err)
	}
	defer rows.Close()

	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			t.Fatalf("could not scan an id: %v", err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("could not read the expected order: %v", err)
	}
	return ids
}

func TestPostgresStoreListStoriesPaginatesWithoutGapsOrRepeats(t *testing.T) {
	env := integrationSetup(t)
	ctx := context.Background()

	const total = 5
	for i := 0; i < total; i++ {
		if _, err := env.store.CreateStory(ctx, newIntegrationStory(env.author, fmt.Sprintf("page-%d", i))); err != nil {
			t.Fatalf("CreateStory(%d) error = %v, want nil", i, err)
		}
	}

	// The pages must tile the feed exactly: no row repeated, none skipped. Only
	// this test's rows are compared, because the feed is global, so the walk is
	// bounded rather than run to the end of a table it does not own.
	want := authoredIDs(t, env)
	mine := make(map[string]bool, len(want))
	for _, id := range want {
		mine[id] = true
	}

	var (
		seen   []string
		cursor *Cursor
		pages  int
	)

	for pages = 0; pages < 50 && len(seen) < len(want); pages++ {
		page, next, err := env.store.ListStories(ctx, cursor, 2)
		if err != nil {
			t.Fatalf("ListStories() error = %v, want nil", err)
		}

		if len(page) > 2 {
			t.Fatalf("page %d has %d rows, want at most 2", pages+1, len(page))
		}
		for _, story := range page {
			if mine[story.ID] {
				seen = append(seen, story.ID)
			}
		}

		if next == nil {
			break
		}
		cursor = next
	}

	if len(seen) != len(want) {
		t.Fatalf("collected %d of this author's stories across %d pages, want %d", len(seen), pages, len(want))
	}
	for i := range want {
		if seen[i] != want[i] {
			t.Fatalf("collected position %d = %s, want %s (pages must tile the feed in created_at DESC, id DESC order)", i, seen[i], want[i])
		}
	}
}

func TestPostgresStoreListStoriesStopsWithoutACursor(t *testing.T) {
	env := integrationSetup(t)
	ctx := context.Background()

	const created = 3
	for i := 0; i < created; i++ {
		if _, err := env.store.CreateStory(ctx, newIntegrationStory(env.author, fmt.Sprintf("last-%d", i))); err != nil {
			t.Fatalf("CreateStory(%d) error = %v, want nil", i, err)
		}
	}

	// The feed is global, and other packages' integration tests run against the
	// same database at the same time, so a row count read here could change
	// before the next read. The assertions therefore use the contract rather
	// than a count: a page never exceeds the limit, and a cursor is returned
	// exactly when the page is full.
	for _, limit := range []int{created, 10} {
		page, next, err := env.store.ListStories(ctx, nil, limit)
		if err != nil {
			t.Fatalf("ListStories(limit=%d) error = %v, want nil", limit, err)
		}

		if len(page) > limit {
			t.Errorf("ListStories(limit=%d) returned %d rows, want at most %d", limit, len(page), limit)
		}
		if next != nil && len(page) != limit {
			t.Errorf("ListStories(limit=%d) returned a cursor with %d rows, want a cursor only when the page is full", limit, len(page))
		}
	}

	// The end of the feed must be reported explicitly rather than by an empty
	// page: a limit larger than the feed returns every row and no cursor.
	page, next, err := env.store.ListStories(ctx, nil, 1000)
	if err != nil {
		t.Fatalf("ListStories(limit=1000) error = %v, want nil", err)
	}
	if next != nil {
		t.Errorf("ListStories(limit=1000) returned a cursor %+v, want nil at the end of the feed", next)
	}
	if len(page) < created {
		t.Errorf("ListStories(limit=1000) returned %d rows, want at least the %d this test created", len(page), created)
	}
}

func TestPostgresStoreListStoriesCursorIsExclusive(t *testing.T) {
	env := integrationSetup(t)
	ctx := context.Background()

	for i := 0; i < 3; i++ {
		if _, err := env.store.CreateStory(ctx, newIntegrationStory(env.author, fmt.Sprintf("excl-%d", i))); err != nil {
			t.Fatalf("CreateStory(%d) error = %v, want nil", i, err)
		}
	}

	first, next, err := env.store.ListStories(ctx, nil, 1)
	if err != nil {
		t.Fatalf("ListStories() error = %v, want nil", err)
	}
	if len(first) != 1 || next == nil {
		t.Fatalf("first page = %d rows with cursor %+v, want 1 row and a cursor", len(first), next)
	}

	second, _, err := env.store.ListStories(ctx, next, 1)
	if err != nil {
		t.Fatalf("ListStories() error = %v, want nil", err)
	}
	if len(second) != 1 {
		t.Fatalf("len(second) = %d, want 1", len(second))
	}

	if second[0].ID == first[0].ID {
		t.Error("the cursor row was returned again, want the comparison to be strictly exclusive")
	}

	// The resumed page must continue in feed order, not merely differ.
	if second[0].CreatedAt.After(first[0].CreatedAt) {
		t.Errorf("second page created at %v is newer than the first page %v, want older", second[0].CreatedAt, first[0].CreatedAt)
	}
	if second[0].CreatedAt.Equal(first[0].CreatedAt) && second[0].ID >= first[0].ID {
		t.Errorf("second page id %s does not sort below %s, want the id tiebreaker to advance", second[0].ID, first[0].ID)
	}
}

func TestPostgresStoreRejectsNilPool(t *testing.T) {
	if _, err := NewPostgresStore(nil); err == nil {
		t.Error("NewPostgresStore(nil) error = nil, want an error")
	}
}

// countAuthorStories counts the stories a single author owns, read with an
// independent query so the rollback assertion is not circular.
func countAuthorStories(t *testing.T, env integrationStore) int {
	t.Helper()

	var total int
	if err := env.pool.QueryRow(
		context.Background(),
		"SELECT count(*) FROM stories WHERE author_id = $1",
		env.author,
	).Scan(&total); err != nil {
		t.Fatalf("could not count stories: %v", err)
	}
	return total
}

func TestPostgresStoreCreateStoryRollsBackWhenVersionInsertFails(t *testing.T) {
	// A story and its root version are written together, so a failure while
	// writing the version must leave no story behind. A NUL byte is valid in a Go
	// string but cannot be stored in a PostgreSQL text column, so putting one in
	// the body makes only the version insert fail: the body column lives on
	// story_versions, not on stories.
	env := integrationSetup(t)
	ctx := context.Background()

	before := countAuthorStories(t, env)

	_, err := env.store.CreateStory(ctx, Story{
		AuthorID:  env.author,
		Pillar:    PillarHeritage,
		Language:  "eng",
		Title:     "Rollback candidate",
		Body:      "this body contains a NUL byte: \x00",
		MediaURLs: []string{},
	})
	if err == nil {
		t.Fatal("CreateStory() error = nil, want the root version insert to fail on the NUL byte")
	}

	if after := countAuthorStories(t, env); after != before {
		t.Errorf("stories for the author = %d, want %d — the story must roll back when its version fails", after, before)
	}
}
