package storymedia

import (
	"context"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// integrationEnv is what the integration tests work with: the store under test,
// the pool, and a story to attach media to.
type integrationEnv struct {
	store  *PostgresStore
	pool   *pgxpool.Pool
	prefix string
	author string
	story  string
}

// integrationSetup connects to the database named by KNOT_POSTGRES_DSN and
// creates an author and a story to attach media to.
//
// The test is skipped, not failed, when KNOT_POSTGRES_DSN is unset, when the
// database is unreachable, or when the tables have not been migrated yet — none
// of those is a defect in the code under test.
func integrationSetup(t *testing.T) integrationEnv {
	t.Helper()

	dsn := strings.TrimSpace(os.Getenv("KNOT_POSTGRES_DSN"))
	if dsn == "" {
		t.Skip("KNOT_POSTGRES_DSN is not set; skipping PostgreSQL integration test")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Skipf("could not build a pool from KNOT_POSTGRES_DSN: %v", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		t.Skipf("PostgreSQL at KNOT_POSTGRES_DSN is not reachable: %v", err)
	}

	var migrated bool
	if err := pool.QueryRow(ctx, "SELECT to_regclass('public.story_media') IS NOT NULL").Scan(&migrated); err != nil {
		pool.Close()
		t.Skipf("could not inspect the schema: %v", err)
	}
	if !migrated {
		pool.Close()
		t.Skip("the story_media table does not exist; run `go run ./cmd/knot migrate up` first")
	}

	store, err := NewPostgresStore(pool)
	if err != nil {
		pool.Close()
		t.Fatalf("NewPostgresStore() error = %v, want nil", err)
	}

	prefix := fmt.Sprintf("knot-sm-it-%d-", time.Now().UnixNano())

	var author string
	err = pool.QueryRow(
		ctx,
		`INSERT INTO users (email, password_hash, display_name, preferred_languages)
		 VALUES ($1, $2, $3, $4)
		 RETURNING id`,
		prefix+"author@example.test",
		"$argon2id$v=19$m=65536,t=1,p=4$c2FsdA$a2V5",
		"Story Media Author",
		[]string{"en"},
	).Scan(&author)
	if err != nil {
		pool.Close()
		t.Fatalf("could not create the integration author: %v", err)
	}

	// A story and its root version reference each other, so they are written by a
	// single statement with two data-modifying CTEs, exactly as the stories store
	// does: with an immediate foreign key neither row can be inserted first.
	var story string
	if err := pool.QueryRow(
		ctx,
		`WITH new_story AS (
			INSERT INTO stories (author_id, pillar, root_version_id)
			VALUES ($1, 'wonder', gen_random_uuid())
			RETURNING id, root_version_id, author_id
		), new_version AS (
			INSERT INTO story_versions (id, story_id, parent_version_id, author_id, language, title, body)
			SELECT root_version_id, id, NULL, author_id, 'en', 'Integration', 'Body' FROM new_story
			RETURNING id
		)
		SELECT id FROM new_story`,
		author,
	).Scan(&story); err != nil {
		pool.Close()
		t.Fatalf("could not create the integration story: %v", err)
	}

	t.Cleanup(func() {
		cleanupCtx, cancelCleanup := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancelCleanup()

		if _, err := pool.Exec(cleanupCtx, "DELETE FROM stories WHERE author_id = $1", author); err != nil {
			t.Logf("cleanup: could not delete test stories: %v", err)
		}
		if _, err := pool.Exec(cleanupCtx, "DELETE FROM users WHERE email LIKE $1", prefix+"%"); err != nil {
			t.Logf("cleanup: could not delete test users: %v", err)
		}
		pool.Close()
	})

	return integrationEnv{store: store, pool: pool, prefix: prefix, author: author, story: story}
}

// newIntegrationMedia builds a media row ready to insert.
func newIntegrationMedia(env integrationEnv, name string, order int) StoryMedia {
	width, height := 100, 200
	return StoryMedia{
		StoryID:      env.story,
		UploaderID:   env.author,
		StorageKey:   StoryMediaKeyPrefix(env.story) + name + ".jpg",
		MediaType:    MediaTypeImage,
		MimeType:     "image/jpeg",
		Source:       MediaSourceCamera,
		Width:        &width,
		Height:       &height,
		SizeBytes:    1234,
		DisplayOrder: order,
	}
}

func TestPostgresStoreCreateMediaRoundTrip(t *testing.T) {
	env := integrationSetup(t)
	ctx := context.Background()

	created, err := env.store.CreateMedia(ctx, newIntegrationMedia(env, "round-trip", -1))
	if err != nil {
		t.Fatalf("CreateMedia() error = %v, want nil", err)
	}

	if !isUUID(created.ID) {
		t.Errorf("id = %q, want a canonical uuid generated by the database", created.ID)
	}
	if created.StoryID != env.story || created.UploaderID != env.author {
		t.Errorf("owner = (%q, %q), want (%q, %q)", created.StoryID, created.UploaderID, env.story, env.author)
	}
	if created.DisplayOrder != 0 {
		t.Errorf("display order = %d, want 0 for the first item", created.DisplayOrder)
	}
	if created.Width == nil || *created.Width != 100 || created.Height == nil || *created.Height != 200 {
		t.Errorf("dimensions = (%v, %v), want (100, 200)", created.Width, created.Height)
	}
	if created.Source != MediaSourceCamera {
		t.Errorf("source = %q, want camera", created.Source)
	}
	if created.CreatedAt.IsZero() {
		t.Error("created at is zero, want a database-generated value")
	}

	fetched, err := env.store.GetMedia(ctx, created.ID)
	if err != nil {
		t.Fatalf("GetMedia() error = %v, want nil", err)
	}
	if fetched.StorageKey != created.StorageKey || fetched.MimeType != created.MimeType {
		t.Errorf("fetched = %+v, want it to match the created row", fetched)
	}
}

func TestPostgresStoreStoriesMediaAuthorAndListing(t *testing.T) {
	env := integrationSetup(t)
	ctx := context.Background()

	author, err := env.store.StoryAuthor(ctx, env.story)
	if err != nil {
		t.Fatalf("StoryAuthor() error = %v, want nil", err)
	}
	if author != env.author {
		t.Errorf("author = %q, want %q", author, env.author)
	}

	if _, err := env.store.StoryAuthor(ctx, "99999999-9999-4999-8999-999999999999"); err != ErrStoryNotFound {
		t.Errorf("StoryAuthor(unknown) error = %v, want ErrStoryNotFound", err)
	}

	// Appending orders items as they are written.
	for i := 0; i < 3; i++ {
		if _, err := env.store.CreateMedia(ctx, newIntegrationMedia(env, fmt.Sprintf("item-%d", i), -1)); err != nil {
			t.Fatalf("CreateMedia(%d) error = %v", i, err)
		}
	}

	page, err := env.store.ListMedia(ctx, env.story)
	if err != nil {
		t.Fatalf("ListMedia() error = %v, want nil", err)
	}
	if len(page) != 3 {
		t.Fatalf("ListMedia() = %d items, want 3", len(page))
	}
	for i, item := range page {
		if item.DisplayOrder != i {
			t.Errorf("item %d display order = %d, want %d", i, item.DisplayOrder, i)
		}
	}

	first, err := env.store.FirstMedia(ctx, []string{env.story, "99999999-9999-4999-8999-999999999999"})
	if err != nil {
		t.Fatalf("FirstMedia() error = %v, want nil", err)
	}
	if got, ok := first[env.story]; !ok || got.ID != page[0].ID {
		t.Errorf("FirstMedia() = %+v, want the first listed item %q", first, page[0].ID)
	}
}

func TestPostgresStoreDeleteMedia(t *testing.T) {
	env := integrationSetup(t)
	ctx := context.Background()

	created, err := env.store.CreateMedia(ctx, newIntegrationMedia(env, "to-delete", -1))
	if err != nil {
		t.Fatalf("CreateMedia() error = %v", err)
	}

	if err := env.store.DeleteMedia(ctx, created.ID); err != nil {
		t.Fatalf("DeleteMedia() error = %v, want nil", err)
	}
	if _, err := env.store.GetMedia(ctx, created.ID); err != ErrNotFound {
		t.Errorf("GetMedia(after delete) error = %v, want ErrNotFound", err)
	}
	if err := env.store.DeleteMedia(ctx, created.ID); err != ErrNotFound {
		t.Errorf("DeleteMedia(again) error = %v, want ErrNotFound", err)
	}
}
