-- 0012_comment_replies — a comment may name the comment it answers.
--
-- Comments were a flat list: every comment belonged to a version and nothing
-- related one comment to another. This migration adds the parent pointer that
-- makes a reply possible (KNOT-ADR-047).
--
-- The parent is nullable, and NULL is the common case: a top-level comment, and
-- every comment a bridge creates, has no parent. A bridge's target comment is a
-- peer in another language, not a reply (KNOT-ADR-014), so bridges are
-- deliberately left out of the thread structure.
--
-- ON DELETE CASCADE, matching the rest of the schema's containment rules: there
-- is no way to delete a comment today, but when there is, deleting a parent
-- should take its replies with it rather than leaving rows pointing at nothing.
--
-- The CHECK is what makes "a comment can never be its own parent" a property of
-- the data rather than a hope: the unique id is generated by PostgreSQL, so the
-- service cannot compare a new comment against its own id, and this is the only
-- layer that can enforce the rule on the create path.
--
-- Idempotent by construction: the column and index use IF NOT EXISTS and the
-- constraint is guarded by a catalogue check, so the file is safe to run twice by
-- hand. The runner records applied versions, so it will not re-run it there.

ALTER TABLE comments
    ADD COLUMN IF NOT EXISTS parent_comment_id UUID NULL REFERENCES comments(id) ON DELETE CASCADE;

-- Replies are looked up by parent when a page of a thread is assembled, so the
-- column needs its own index: the thread's other index is keyed by version.
CREATE INDEX IF NOT EXISTS comments_parent_comment_id_idx ON comments (parent_comment_id);

-- A comment cannot be its own parent. PostgreSQL has no ADD CONSTRAINT IF NOT
-- EXISTS, so the catalogue is checked first.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'comments_parent_comment_id_not_self'
          AND conrelid = 'comments'::regclass
    ) THEN
        ALTER TABLE comments
            ADD CONSTRAINT comments_parent_comment_id_not_self
            CHECK (parent_comment_id IS NULL OR parent_comment_id <> id);
    END IF;
END
$$;
